image: node:14.15.1

pipelines:
  default:
      - step:
          name: Build and Deploy Dinamic Branch
          script:
            # Instala as dependÍncias e faz o build
            - npm install
            - npm run build
            - export BRANCH=$BITBUCKET_BRANCH
            - export BUCKET_NAME=${BRANCH}-app.verum.digital       
            # Faz o deploy dos arquivos para o bucket S3 da AWS
            - apt-get update -y && apt-get upgrade -y 
            - apt-get install -y python3-pip
            - pip3 install awscli
            - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            #cria o bucket e aplica as configuracoes necessarias
            - aws s3api create-bucket --bucket $BUCKET_NAME --region us-east-1
            - aws s3 website s3://$BUCKET_NAME --index-document index.html --error-document error.html
            - echo '{"Version":"2012-10-17","Statement":[{"Sid":"AllowPublicReadAccess","Effect":"Allow","Principal":"*","Action":"s3:GetObject","Resource":"arn:aws:s3:::${BUCKET_NAME}/*"}]}' > policy.json
            - aws s3api put-bucket-policy --bucket $BUCKET_NAME --policy policy.json
            - aws s3 sync build/ s3://$BUCKET_NAME

  branches:
    master:
      - step:
          name: Deploy to master
          caches:
                - pip                
          script:
            - echo "Deploy to STG"             
            # Instala as dependÍncias e faz o build
            - npm install
            - npm run build
            #- aws s3api create-bucket --bucket nome-do-seu-bucket --region us-west-2

            # Faz o deploy dos arquivos para o bucket S3 da AWS
            - apt-get update && apt-get install -y python3-pip
            - pip install --upgrade pip  
            - pip3 install awscli
            - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            - aws s3 sync build/ s3://master-app.verum.digital
      - step:
          name: Deploy to production
          trigger: manual
          script:
            - echo "Deploying to production"
            # Instala as dependÍncias e faz o build
            - npm install
            - npm run build
            #- aws s3api create-bucket --bucket nome-do-seu-bucket --region us-west-2

            # Faz o deploy dos arquivos para o bucket S3 da AWS
            - apt-get update && apt-get install -y python3-pip
            - pip3 install awscli
            - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            - aws s3 sync build/ s3://app.verum.digital